[server]
backlog = 10000
cert_file = "certificates/localhost.crt"
http_port = 8081
https_port = 1443
keep_alive = 0
key_file = "certificates/localhost.key"
max_connection_rate = 1000
max_connections = 10000
max_frame_size = 134217728
workers = 8

[frontend_mgr]
frontends = [
  {domain = "localhost", public_ip = "127.0.0.1", private_ip = "127.0.0.1", http_port = 10000, https_port = 11443},
]

[backend_mgr]
backends = [
  {private_ip = "127.0.0.1", http_port = 20000},
]

[service_mgr]
stale_threshold = 1800 # seconds
unhealthy_threshold = 60 # seconds

[db]
path = "data"

[db.seriesdb]
level_zero_file_num_compaction_trigger = 4
max_background_jobs = 4
max_bytes_for_level_base = 1073741824
max_bytes_for_level_multiplier = 8.0
max_write_buffer_number = 4
min_write_buffer_number_to_merge = 2
table_cache_num_shard_bits = 4
target_file_size_base = 134217728
target_file_size_multiplier = 8
write_buffer_size = 134217728
