# Scan this file for changes every 30 seconds
refresh_rate: 30 seconds

appenders:
  # An appender named "console" that writes to console
  console:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {h({l})} <{I}> {M}:{L} - {m}{n}"

  # An appender named "file" that writes to a file with a custom pattern encoder
  # and a custom policy
  file:
    kind: rolling_file
    path: "log/app.log"
    append: true
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {h({l})} <{I}> {M}:{L} - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        pattern: "log/app.log.{}"
        base: 1
        count: 5

# Set the default logging level to "info" and attach the "stdout" appender
# and the "file" appender to the root
root:
  level: info
  appenders:
    - console
    - file
